### ISSUE TITLE
Error during my first tests

### ISSUE THREAD

**Issue by Chapeaunyra** [thewhiteh4t/nexfil#17]
First time i'm sending an issue, but here we go.

I've cloned your repository, followed your instructions then I tried to use `python3 nexfil.py -u Chapeaunyra`.

This is the response, truncate before the error.

```
Traceback (most recent call last):
  File "nexfil.py", line 276, in test_redirect
    response = await session.head(url, allow_redirects=False)
  File "/home/valentin/.local/lib/python3.7/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/valentin/.local/lib/python3.7/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nexfil.py", line 142, in query
    await test_redirect(session, url)
  File "nexfil.py", line 277, in test_redirect
    except asyncio.exceptions.TimeoutError:
AttributeError: module 'asyncio' has no attribute 'exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nexfil.py", line 379, in <module>
    launch(uname)
  File "nexfil.py", line 358, in launch
    loop.run_until_complete(main(uname))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "nexfil.py", line 342, in main
    await asyncio.gather(*tasks)
  File "nexfil.py", line 167, in query
    except asyncio.exceptions.TimeoutError:
AttributeError: module 'asyncio' has no attribute 'exceptions'
```

I'm on Debian 10, Buster.
Let me know if u need more informations and which one would be able to help you to improve your tool :)

**Comment by thewhiteh4t** [comment]
@Chapeaunyra upgrade to py3.9

**Comment by pinak9** [comment]
Hello,

I tried compiling the requirements.txt and I got the below error, I have python 3.10 instaled.

 ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hiral Dave\\AppData\\Local\\Temp\\pip-install-fqdwlh1c\\cchardet_c7a3e4e7293e46f994402738b03f5c73\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hiral Dave\\AppData\\Local\\Temp\\pip-install-fqdwlh1c\\cchardet_c7a3e4e7293e46f994402738b03f5c73\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hiral Dave\AppData\Local\Temp\pip-record-lglj0ay9\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Hiral Dave\AppData\Roaming\Python\Python310\Include\cchardet'
         cwd: C:\Users\Hiral Dave\AppData\Local\Temp\pip-install-fqdwlh1c\cchardet_c7a3e4e7293e46f994402738b03f5c73\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\cchardet
    copying src\cchardet\version.py -> build\lib.win-amd64-3.10\cchardet
    copying src\cchardet\__init__.py -> build\lib.win-amd64-3.10\cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hiral Dave\\AppData\\Local\\Temp\\pip-install-fqdwlh1c\\cchardet_c7a3e4e7293e46f994402738b03f5c73\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hiral Dave\\AppData\\Local\\Temp\\pip-install-fqdwlh1c\\cchardet_c7a3e4e7293e46f994402738b03f5c73\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hiral Dave\AppData\Local\Temp\pip-record-lglj0ay9\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Hiral Dave\AppData\Roaming\Python\Python310\Include\cchardet' Check the logs for full command output.

**Comment by thewhiteh4t** [comment]
@pinak9 the solution to the error is in the error itself, read carefully

**Comment by pinak9** [comment]
> @pinak9 the solution to the error is in the error itself, read carefully

Ah I see it thanks.. I am blind lol
