### ISSUE TITLE
nexfil on windows

### ISSUE THREAD

**Issue by swagkarna** [thewhiteh4t/nexfil#2]
cant we use this in windows?

**Comment by swagkarna** [comment]
![Screenshot (146)](https://user-images.githubusercontent.com/46685308/119238605-15fc2500-bb61-11eb-80ba-3281c955eda3.png)

**Comment by swagkarna** [comment]
ok we cant use in windows right?

**Comment by swagkarna** [comment]
![Screenshot (147)](https://user-images.githubusercontent.com/46685308/119238846-c6b6f400-bb62-11eb-9b2a-1dd93eb535d9.png)

**Comment by swagkarna** [comment]
Screenshot 1 :  I Have fixed by removing ./local/share/neflix

Screenshot 2 : simple error u have used with open('url_store.json', 'r') as url_store: instead of 'r' i used 'rb' 

Now it works fine

**Comment by swagkarna** [comment]
![Uploading Screenshot (148).png…]()

**Comment by swagkarna** [comment]
![Screenshot (148)](https://user-images.githubusercontent.com/46685308/119239042-e4388d80-bb63-11eb-95f6-fe1fbc6824b7.png)

**Comment by swagkarna** [comment]
![Screenshot (149)](https://user-images.githubusercontent.com/46685308/119239082-442f3400-bb64-11eb-9489-c01e5d76f706.png)

**Comment by thewhiteh4t** [comment]
@swagkarna no windows is not supported, I am not sure if I will add support for windows, but it should work in WSL on windows

**Comment by graysuit** [comment]
nice cmd

**Comment by swagkarna** [comment]
@graysuit i have made to support windows too go and check in pull requesrt and i have solved my issue

**Comment by swagkarna** [comment]
@graysuit https://github.com/thewhiteh4t/nexfil/pull/4

**Comment by graysuit** [comment]
By the way, script is simple.
The preferred lang for me is javascript which can be used in every browser, locally or remotely.

**Comment by swagkarna** [comment]
@graysuit im currently learning nodejs a simple telegram will be comping soon on my github
