### ISSUE TITLE
cchardet failing install on Python 3.11

### ISSUE THREAD

**Issue by kmnunley** [thewhiteh4t/nexfil#24]
cchardet is failing to install on Python 3.11 and appears to have been abandoned by its developer.

https://github.com/PyYoshi/cChardet/issues/81

**Comment by cclauss** [comment]
Upgrading to https://github.com/Ousret/charset_normalizer is probably the best workaround.

**Comment by thewhiteh4t** [comment]
@Halkenguard aiohttp required cchardet in past and they have already switched to charset_normalizer, I have removed cchardet from requirements.txt
