### ISSUE TITLE
instagram false positive

### ISSUE THREAD

**Issue by torqueperformancega** [thewhiteh4t/nexfil#29]
Searching for Instagram is broken.

![image](https://user-images.githubusercontent.com/120198167/206739551-f0e21276-9d34-46e6-b697-3d46a9cc4bdc.png)

https://www.instagram.com/on3performance/

please fix it

**Comment by thewhiteh4t** [comment]
@torqueperformancega thanks for reporting, I will look into it

**Comment by ahelmy** [comment]
Its working normally 
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/7501254/210134115-a2797b5d-ccb0-42dc-934a-51ebd9eea132.png">
