### ISSUE TITLE
Support For Termux!

### ISSUE THREAD

**Issue by sumit-buddy** [thewhiteh4t/nexfil#3]
I'm trying to run **nexfil** on [termux](https://f-droid.org/en/packages/com.termux/). All requirements are satisfied, still I'm getting the following error 🤕 :

![Screenshot_2021-05-23-08-51-15-895_com termux](https://user-images.githubusercontent.com/67678753/119247096-ae67c900-bba4-11eb-827d-e4aff9cf78a7.jpg)

**Comment by thewhiteh4t** [comment]
@sumit-buddy thanks for reporting, I will look into it

**Comment by thewhiteh4t** [comment]
https://github.com/saghul/aiodns/issues/98

**Comment by MrKnight01** [comment]
> I'm

Try Littlebrother tool for this

**Comment by thewhiteh4t** [comment]
@sumit-buddy fixed in version `1.0.1`
