### ISSUE TITLE
lots of false positives due to cloudflare protection

### ISSUE THREAD

**Issue by thewhiteh4t** [thewhiteh4t/nexfil#34]
working on it, fix coming soon

**Comment by thewhiteh4t** [comment]
https://github.com/thewhiteh4t/nexfil/issues/33

**Comment by thewhiteh4t** [comment]
https://github.com/thewhiteh4t/nexfil/issues/29

**Comment by jacket430** [comment]
I assume this is related, but I get a ton of junk show up when I type pretty much any username. Here's an example.

![Test](https://i.imgur.com/jqy8zej.png)

**Comment by thewhiteh4t** [comment]
@jacket430 yes it is related, I will be pushing an update soon, almost fixed it
