### ISSUE TITLE
Little problem execution

### ISSUE THREAD

**Issue by LiamSeddaoui** [thewhiteh4t/nexfil#35]
Hello dear theWhiteh4t,

I have discover your tool with the video content of Saltinbank (Youtube).
When i execute the script after install the requirements, i have this error :

```
Traceback (most recent call last):
  File "/home/numidian/Bureau/Nexfil/nexfil.py", line 273, in <module>
    log_writer('----- STARTING -----')
  File "/home/numidian/Bureau/Nexfil/modules/write_log.py", line 6, in log_writer
    logging.basicConfig(
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/numidian/.local/share/nexfil/exceptions.log'
```

Please could you help me ?

Thank's in advance & congrats for your job

**Comment by thewhiteh4t** [comment]
@LiamSeddaoui please check if the path `/home/numidian/.local/share/nexfil` exists

**Comment by thewhiteh4t** [comment]
@LiamSeddaoui please update, try :
```
cd nexfil
git pull
```

**Comment by reynadan** [comment]
Hello, @thewhiteh4t, 
sadly still not working 

![image](https://user-images.githubusercontent.com/9109378/208387046-588301fa-ecbc-4e94-a5b0-d8d179baad61.png)

**Comment by thewhiteh4t** [comment]
@reynadan you are using python 3.8, maybe its due to that, I tested on 3.10 and its working fine

**Comment by LiamSeddaoui** [comment]
Hello dear Whiteh4t,

I tried the git pull and re-running the script but it still doesn't work.
I confirm that I have no trace of nexfil in my .local =(

![image](https://user-images.githubusercontent.com/75535261/208388625-ec01f0fa-7ee6-4195-a4b7-411371caa77b.png)

**Comment by LiamSeddaoui** [comment]
Everything works perfectly, thank you very much for your help.


The problem came from me, I deleted the directory and re-clone without retouching the name nor the directory after the cloning and everything works perfectly :D

![image](https://user-images.githubusercontent.com/75535261/208392507-38856975-947c-4080-b871-4115776b8d5f.png)


Thank you and again bravo for your work
