### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by carlsmedstad** [thewhiteh4t/nexfil#41]
Hey,

Do you have any ambitions to add a `setup.py` file and publish this on PyPI? It would make installing it a bit easier. I could submit a PR with the missing pieces if you'd like.

Thanks!

**Comment by carlsmedstad** [comment]
Hey again,

I maintain a [package](https://aur.archlinux.org/packages/nexfil) for this software in the Arch User Repository and I'd happily submit a PR implementing a proper Python package for this project. Is this something you could imagine merging?

Much appreciated, thanks!

**Comment by thewhiteh4t** [comment]
@carlsmedstad thanks a lot for bringing nexfil to AUR, please do submit a PR for this, I also think that it will make the installation much easier, I have some doubts about how `setup.py` will handle non python components after the last update such as requirement of chrome/chromium, your PR will be very helpful in learning about this

**Comment by carlsmedstad** [comment]
Thanks for merging! Would you mind also bumping the version? Much appreciated.

**Comment by thewhiteh4t** [comment]
@carlsmedstad updated!
