### ISSUE TITLE
Default value incorrect

### ISSUE THREAD

**Issue by patr1ckbat3man** [thewhiteh4t/nexfil#44]
This isn't much of an issue, rather than a small mistake? In the argparse help the timeout default is said to be 5:
```python3
parser.add_argument('-t', help='Specify timeout [Default : 5]', type=int)
```
but when setting the defaults, the value is set to 10
```python3
parser.set_defaults(
    t=10,
    v=False,
    U=False,
    pm='single',
    proto='http'
)
```

**Comment by thewhiteh4t** [comment]
@patr1ckbat3man thanks, yeah looks like I did not update the description
