### ISSUE TITLE
Time out Error

### ISSUE THREAD

**Issue by swagkarna** [thewhiteh4t/nexfil#5]
I Have tested this script on windows it woks fine .But when i run this script on ubuntu with python3.7 it throws an error

I Have Attached screenshot Below

![Screenshot (152)](https://user-images.githubusercontent.com/46685308/119254614-e981f080-bbd4-11eb-9893-eb49cf926e83.png)

**Comment by thewhiteh4t** [comment]
@swagkarna updating to python 3.9 should fix this error, iirc 3.9 is available in ubuntu repos

**Comment by swagkarna** [comment]
Mention all these details in your readme section
