### ISSUE TITLE
No support for whitespaces.

### ISSUE THREAD

**Issue by NotepadExpert** [thewhiteh4t/nexfil#7]
There seem to be a bug in  the way the program handles multi-word nicks/names. It can't handle the space in-between the words. 

Proposed solutions:
1) replace the space between the words with the valid web domain character like '-' for subdomain checks, alternatively remove all white spaces (strip)
2) urlencode the string before passing it as a path

**Comment by thewhiteh4t** [comment]
@NotepadExpert please share a valid username and link to some of the profiles so that I can reproduce the issue

**Comment by NotepadExpert** [comment]
@thewhiteh4t Wow that was a quick reply :D Great job. 

Here is an example I used. 
```
python nexfil.py -l "walter xyz,walter abc"

```
It can't resolve the domain names because domains can't have space in their names. Some websites will also fail requests with whitespaces in the url path. I noticed the program attempts to url escape in some cases but most attempts include the space.

**Comment by thewhiteh4t** [comment]
@NotepadExpert thanks for sharing the username, it will be great if you can share valid links to these profiles
